---
name: Build and Deploy

# Docs
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

on:
  push:
    tags:
      - '*'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ github.ref == 'refs/heads/master' && 'ghcr.io/ianneub/gh-runner:latest' || '' }}  
            ghcr.io/ianneub/gh-runner:${{ github.ref_name }}
